# Generated by Django 5.2 on 2025-04-25 09:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'บัตรเครดิต'), ('paypal', 'เพย์พาล')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
